version: '3.1'

services:
    postgres:
        container_name: easy-vet-postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
        volumes:
            - /c/docker-volumes/easy-vet-postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
